# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Server info
      run: uname -a
    - name: Install librsync
      run: brew install librsync
    - name: Set up compiler paths
      run: |
        BREW_PREFIX=$(brew --prefix)
        echo "CPATH=$BREW_PREFIX/include" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$BREW_PREFIX/lib" >> $GITHUB_ENV
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Server info
      run: uname -a
    - name: Install librsync
      run: sudo apt-get update && sudo apt-get install -y librsync-dev
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
