# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Server info
      run: uname -a 
    - name: Install librsync
      run: brew install librsync pkg-config
    - name: Fix pkg-config path
      run: |
        echo "PKG_CONFIG_PATH=$(brew --prefix librsync)/lib/pkgconfig" >> $GITHUB_ENV
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
